import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

import img1 from "assets/images/book-covers/you-can-win.jpg";
import img2 from "assets/images/book-covers/lets-talk-money.jpg";
import img3 from "assets/images/book-covers/think-and-grow-rich.jpg";
import img4 from "assets/images/book-covers/chanakya-neeti.jpg";
import img5 from "assets/images/book-covers/savarkar.jpg";
import img6 from "assets/images/book-covers/one-arr-mur.jpg";
import img7 from "assets/images/book-covers/savarkar2.jpg";
import img8 from "assets/images/book-covers/yolo.jpg";
import img9 from "assets/images/book-covers/auto-yogi.jpg";
import img10 from "assets/images/book-covers/psychology-of-money.jpg";
import img11 from "assets/images/book-covers/it-ends-with-us.jpg";
import img12 from "assets/images/book-covers/to-kill-a-mocking-bird.jpg";
import img13 from "assets/images/book-covers/qa.jpg";
import img14 from "assets/images/book-covers/gate.jpg";
import img15 from "assets/images/book-covers/gulzar.jpg";

export const products = [
  {
    _id: uuid(),
    bookTitle: "You Can WIN",
    author: "Shiv Khera",
    categoryName: "nonfiction",
    prodImg: img1,
    price: "110",
    origPrice: "250",
    coverType: "paperback",
    inStock: false,
    fastDelivery: true,
    rating: "3.2",
  },
  {
    _id: uuid(),
    bookTitle: "Let's Talk Money",
    author: "Monika Halan",
    categoryName: "selfhelp",
    prodImg: img2,
    price: "210",
    origPrice: "450",
    coverType: "hardcover",
    inStock: true,
    fastDelivery: false,
    rating: "4.3",
  },
  {
    _id: uuid(),
    bookTitle: "Think and Grow Rich",
    author: "Napoleon Hill",
    categoryName: "selfhelp",
    prodImg: img3,
    price: "199",
    origPrice: "1000",
    coverType: "paperback",
    inStock: false,
    fastDelivery: false,
    rating: "3.9",
  },
  {
    _id: uuid(),
    bookTitle: "Chanakya Neeti",
    author: "Ashwini Parashar",
    categoryName: "nonfiction",
    prodImg: img4,
    price: "149",
    origPrice: "449",
    coverType: "paperback",
    inStock: true,
    fastDelivery: true,
    rating: "4.2",
  },
  {
    _id: uuid(),
    bookTitle: "Savarkar - Part 1",
    author: "Vikram Sampath",
    price: "249",
    categoryName: "nonfiction",
    prodImg: img5,
    origPrice: "499",
    coverType: "hardcover",
    inStock: true,
    fastDelivery: false,
    rating: "4.3",
  },
  {
    _id: uuid(),
    bookTitle: "One Arranged Murder",
    author: "Chetan Bhagat",
    price: "149",
    categoryName: "fiction",
    prodImg: img6,
    origPrice: "599",
    coverType: "paperback",
    inStock: false,
    fastDelivery: false,
    rating: "1.8",
  },
  {
    _id: uuid(),
    bookTitle: "Savarkar - Part II",
    author: "Vikram Sampath",
    price: "249",
    categoryName: "nonfiction",
    prodImg: img7,
    origPrice: "499",
    coverType: "hardcover",
    inStock: true,
    fastDelivery: false,
    rating: "4.5",
  },
  {
    _id: uuid(),
    bookTitle: "You Only Live Once",
    author: "Stuti Changle",
    price: "149",
    categoryName: "fiction",
    prodImg: img8,
    origPrice: "449",
    coverType: "paperback",
    inStock: false,
    fastDelivery: true,
    rating: "2.8",
  },
  {
    _id: uuid(),
    bookTitle: "Autobiography of a yogi",
    author: "Paramhansa Yogananda",
    price: "149",
    categoryName: "nonfiction",
    prodImg: img9,
    origPrice: "449",
    coverType: "paperback",
    inStock: true,
    fastDelivery: false,
    rating: "3.8",
  },
  {
    _id: uuid(),
    bookTitle: "Psychology of Money",
    author: "Morgan Housel",
    price: "149",
    categoryName: "selfhelp",
    prodImg: img10,
    origPrice: "449",
    coverType: "paperback",
    inStock: true,
    fastDelivery: true,
    rating: "4.5",
  },
  {
    _id: uuid(),
    bookTitle: "It Ends With Us",
    author: "Colleen Hoover",
    price: "249",
    categoryName: "fiction",
    prodImg: img11,
    origPrice: "899",
    coverType: "Hardcover",
    inStock: true,
    fastDelivery: true,
    rating: "2.9",
  },
  {
    _id: uuid(),
    bookTitle: "To Kill a mocking bird",
    author: "Colleen Hoover",
    price: "99",
    categoryName: "fiction",
    prodImg: img12,
    origPrice: "249",
    coverType: "paperback",
    inStock: true,
    fastDelivery: false,
    rating: "3.6",
  },
  {
    _id: uuid(),
    bookTitle: "Quantitative Aptitude",
    author: "RS Agrawal",
    price: "99",
    categoryName: "exams",
    prodImg: img13,
    origPrice: "249",
    coverType: "paperback",
    inStock: true,
    fastDelivery: true,
    rating: "4.3",
  },
  {
    _id: uuid(),
    bookTitle: "CS-IT GATE 2020",
    author: "Pearson",
    price: "499",
    categoryName: "exams",
    prodImg: img14,
    origPrice: "899",
    coverType: "paperback",
    inStock: true,
    fastDelivery: true,
    rating: "3.6",
  },
  {
    _id: uuid(),
    bookTitle: "Selected Poems",
    author: "Gulzar",
    price: "199",
    categoryName: "poetry",
    prodImg: img15,
    origPrice: "799",
    coverType: "hardcover",
    inStock: true,
    fastDelivery: true,
    rating: "4.8",
  },
];
